### PR TITLE
add heparinase to reference fasta

### PR DESCRIPTION
**Pull request by rpetit3**
This is related to https://github.com/CFSAN-Biostatistics/shigatyper/issues/6

Adds the gene sequence for heparinase (https://www.ncbi.nlm.nih.gov/nuccore/CP016036.1?from=2803&to=4428&report=fasta&strand=2) required for calling `Shigella boydii serotype 20`

Without `heparinase` in reference fasta
```
sample  prediction      ipaB
SRX1486859      Shigella boydii serotype 1      -
```

With `heparinase` in reference fasta
```
sample  prediction      ipaB
SRX1486859      Shigella boydii serotype 20     -
```

### CODE REVIEW

**Comment by florathecat** [comment]
Thanks Robert,

We just realized the missing heparinase gene from the reference fasts file and have not add it back. Can you please merge your loop with all your fixes?

I’ll get to it later with the shigatoxins after I figure out what else are missing. 

Thanks,

**Comment by rpetit3** [comment]
By "all you fixes", do you mean adding single-end and ont support?

**Comment by florathecat** [comment]
Yes please. I guess I wasn’t being explicit. My apologies.

**Comment by rpetit3** [comment]
Going to close this in favor of https://github.com/CFSAN-Biostatistics/shigatyper/pull/9

**Pull request closed without merging**
